import type { NextRequest } from 'next/server'
import {
  getServiceRoleClient,
  isPublicSlug,
  type ClientRow,
  type VoiceProfileRow,
} from '@/lib/supabase'

export const dynamic = 'force-dynamic'

const NOT_FOUND = new Response('Not found\n', {
  status: 404,
  headers: { 'Content-Type': 'text/plain; charset=utf-8' },
})

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params

  if (!isPublicSlug(slug)) return NOT_FOUND

  const sb = getServiceRoleClient()

  const { data: client, error } = await sb
    .from('wv_be_clients')
    .select('id, display_name, industry, metadata, updated_at')
    .eq('metadata->>slug', slug)
    .is('deleted_at', null)
    .maybeSingle<ClientRow>()

  if (error || !client) return NOT_FOUND
  if (client.metadata?.internal_only === true) return NOT_FOUND

  const { data: vp } = await sb
    .from('wv_be_voice_profiles')
    .select('audience, one_word_tone, register')
    .eq('client_id', client.id)
    .maybeSingle<Pick<VoiceProfileRow, 'audience' | 'one_word_tone' | 'register'>>()

  const bf = client.metadata?.brand_facts ?? {}

  const name = bf.name ?? client.display_name
  const description = bf.mission ?? `${name} — brand profile`
  const ogUrl = `https://app.brandhacker.com/${slug}`
  const ogImage = `https://brandhacker.com/${slug}/og-image.png`

  // og:description capped at 200 chars for safe meta tag length
  const ogDescription =
    description.length > 200 ? description.slice(0, 197) + '...' : description

  // twitter:description — typically shorter (max 200 chars, same cap is fine)
  const twitterDescription = ogDescription

  // Build audience hint for twitter:label — use voice profile audience if available
  const audienceHint = vp?.audience ?? null

  const lines: string[] = [
    `<!-- OpenGraph meta tags for ${name} — generated by BrandHacker -->`,
    `<!-- Source: https://app.brandhacker.com/${slug}/og-meta -->`,
    '',
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="${escapeAttr(name)}" />`,
    `<meta property="og:title" content="${escapeAttr(name)}" />`,
    `<meta property="og:description" content="${escapeAttr(ogDescription)}" />`,
    `<meta property="og:url" content="${escapeAttr(ogUrl)}" />`,
    `<meta property="og:image" content="${escapeAttr(ogImage)}" />`,
    '',
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${escapeAttr(name)}" />`,
    `<meta name="twitter:description" content="${escapeAttr(twitterDescription)}" />`,
    `<meta name="twitter:image" content="${escapeAttr(ogImage)}" />`,
    ...(audienceHint
      ? [
          `<meta name="twitter:label1" content="Audience" />`,
          `<meta name="twitter:data1" content="${escapeAttr(audienceHint)}" />`,
        ]
      : []),
  ]

  // Crawl log — best-effort
  await sb
    .from('wv_be_aeo_crawl_log')
    .insert({
      client_id: client.id,
      artefact_type: 'og_meta',
      user_agent: req.headers.get('user-agent') ?? '(none)',
      ip_hash: null,
    })
    .then(() => undefined, () => undefined)

  return new Response(lines.join('\n') + '\n', {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
      'X-BrandHacker-Schema': 'og-meta v1',
      'X-BrandHacker-Tenant': slug,
    },
  })
}

/** Escape characters unsafe in HTML attribute values */
function escapeAttr(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}
